/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsMarketIdRouteImport } from './routes/markets.$marketId'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faucet': typeof FaucetRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faucet': typeof FaucetRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/faucet': typeof FaucetRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/portfolio': typeof PortfolioRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faucet'
    | '/login'
    | '/orders'
    | '/portfolio'
    | '/markets/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faucet'
    | '/login'
    | '/orders'
    | '/portfolio'
    | '/markets/$marketId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faucet'
    | '/login'
    | '/orders'
    | '/portfolio'
    | '/markets/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FaucetRoute: typeof FaucetRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PortfolioRoute: typeof PortfolioRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FaucetRoute: FaucetRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PortfolioRoute: PortfolioRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
